# Copyright 2024 <lhearachel@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
.PHONY: check check-dep-exists format pre-commit valgrind

check: format pre-commit

check-dep-exists:
	@if ! command -v $(DEP_TARGET) &> /dev/null; then \
		echo "$(DEP_TARGET) not found"; \
		exit 1; \
	fi

format: DEP_TARGET=clang-format
format: .clang-format check-dep-exists
	clang-format -i --style=file $(ALLSRC) $(ALLINC)

pre-commit: DEP_TARGET=pre-commit
pre-commit: .pre-commit-config.yaml check-dep-exists
	pre-commit run

valgrind: debug
	valgrind --leak-check=full \
		--show-leak-kinds=all \
		--track-origins=yes \
		--verbose \
		--log-file=valgrind.log \
		./$(TARGET) $(ARGS)
